obj-$(CONFIG_RAETH) += raeth.o
raeth-objs := ra_mac.o mii_mgr.o
raeth-objs += raether_pdma.o
EXTRA_CFLAGS   += -DWORKQUEUE_BH
#EXTRA_CFLAGS   += -DCONFIG_RAETH_MULTIPLE_RX_RING

raeth-objs += raether.o
